CREATE TABLE IF NOT EXISTS b0d_pairing (
 code_hash CHAR(64) PRIMARY KEY,
 device_id UUID NOT NULL REFERENCES b0d_devices(id),
 expires_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS b0d_pair_guard (
 id INTEGER PRIMARY KEY CHECK(id=1),
 attempts INTEGER NOT NULL DEFAULT 0,
 window_start TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO b0d_pair_guard(id) VALUES(1) ON CONFLICT DO NOTHING;
INSERT INTO b0d_schema_version VALUES(4) ON CONFLICT DO NOTHING;
